# Generated by Codex on 2026-08-27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('gstin_or_tax_id', models.CharField(max_length=50)),
                ('business_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?[0-9]{7,15}$')])),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['verification_status', '-created_at'],
            },
        ),
    ]
