# Generated by Django 6.1 on 2026-08-31 04:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_storefront_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shown only to approved dealers. Leave blank to charge dealers the regular price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
